### PR TITLE
Fix workflow and bulk update facet display of missing values 

### LINKED ISSUE #441: The workflow and bulk update facets have -99999999999 as a value - should be removed
This appeared after adding the "allow missing" checkbox to facets on the facet bar and presearch area. "Allow Missing" doesn't apply to these other settings in workflow and bulk update.

Sample link and screen shot below

https://covid.clinwiki.org/study/NCT04276896/workflow?hash=xJICh0wT&sv=default

image

### PR DESCRIPTION
**Pull request by relwell**
* Fix a bug where you couldn't select "allow missing" for pre-search view site config
* Don't show missing value as an option for a bulk label
* Don't show the missing value as a suggested label in workflow (I had a hard time getting this to display on my local instance, so I just found where it was in the code)

(resolves #441)

### CODE REVIEW

File: front/app/containers/BulkEditPage/BulkEditView.tsx [hunk 1]
```diff
@@ -122,6 +123,10 @@ class BulkEditView extends React.Component<BulkEditProps, BulkEditState> {
                     const isToRemove =
                       groupedByLabel.toRemove[label] &&
                       groupedByLabel.toRemove[label].includes(value);
+                    if (bucketKeyStringIsMissing(value)) {
```
Comment (relwell) [inline front/app/containers/BulkEditPage/BulkEditView.tsx:126]: there are going to be cases where we actually will want to operate over `keyAsString`, but it gets ignored here. cases for that would be dates, where `keyAsString` is a much better way to reason over the aggs than the native key is.

File: front/app/containers/SearchPage/components/AggFilterInputUpdater.tsx [hunk 2]
```diff
@@ -60,7 +60,7 @@ abstract class AbstractAggFilterInputUpdater {
     this.configureInput();
   }
 
-  abstract onUpdateFilter(): void;
+  abstract onUpdateFilter(allowsMissingChanged?: boolean): void;
```
Comment (relwell) [inline front/app/containers/SearchPage/components/AggFilterInputUpdater.tsx:63]: this lets us hook into the change we're making to change what we push onto the site config mutation argument list.

File: front/app/containers/SearchPage/components/AggFilterInputUpdater.tsx [hunk 3]
```diff
@@ -137,37 +137,33 @@ abstract class AbstractAggFilterInputUpdater {
...
-          return this.isDateAgg()
-            ? moment(this.input.gte)
-                .utc(false)
-                .format('YYYY-MM-DD')
-            : this.input.gte;
-        case 'NUMBER_RANGE':
-          return this.input.gte;
-        default:
-          return this.input.gte;
+      const thisField: any =
```
Comment (relwell) [inline front/app/containers/SearchPage/components/AggFilterInputUpdater.tsx:140]: this appears to just be prettier autocorrecting

File: front/app/utils/aggs/bucketKeyIsMissing.ts [hunk 4]
```diff
@@ -4,13 +4,21 @@ import {
...
-    key == STRING_MISSING_IDENTIFIER ||
     keyAsString === STRING_MISSING_IDENTIFIER ||
-    key === DATE_MISSING_IDENTIFIER ||
     keyAsString === DATE_MISSING_IDENTIFIER
   );
 }
+
+function bucketKeyIsMissing(bucket: AggBucket): boolean {
+  return (
+    bucketKeyStringIsMissing(bucket.key) ||
```
Comment (relwell) [inline front/app/utils/aggs/bucketKeyIsMissing.ts:20]: i broke these out to make the comparison more useful in different parts for now, but we should probably be operating over these buckets in those places so we can better utilize the key as string functionality for rendering things like dates.
